---
title: "Doorae_data"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

### Data 

* Reading data with xlsx
     + Note the arguments `stringsAsFactors` and `encoding` 
     + `knitr` 에서 default로 `R` 폴더를 작업 디렉토리로 설정함에 유의.
     
```{r, data_xlsx}
library(xlsx)
library(knitr)
doorae0924.rest <- read.xlsx("../data/Data0924.xlsx", 1, colIndex = 2:54, endRow = 98, stringsAsFactors = TRUE, encoding = "UTF-8")
doorae0924.name <- read.xlsx("../data/Data0924.xlsx", 1, colIndex = 1, endRow = 98, stringsAsFactors = FALSE, encoding = "UTF-8")
doorae0924 <- data.frame(doorae0924.name, doorae0924.rest)
```

### Data cleaning

```{r, data anomaly}
doorae0924$"시도"
```

* 전북이 두 개 나옴에 유의. 어떤 사연인가 하면,

```{r, data cleaning}
(id.to.fix <- which(doorae0924$"시도"=="전북 "))
doorae0924$"조직명"[id.to.fix]
doorae0924$"시도"[id.to.fix] <- "전북"
doorae0924$"시도"
kable(t(as.matrix(table(doorae0924$"시도"))))
```

* count가 없는 factor level도 손봐야 함. 이는 간단히

```{r, removing null factor level}
(doorae0924$"시도" <- factor(doorae0924$"시도"))
kable(t(as.matrix(table(doorae0924$"시도"))))
```

### Data for Years in Business

* 업력(years in business) 계산

```{r, difftime}
str(doorae0924)
years.in.business <- round(as.numeric(difftime(Sys.Date(), doorae0924$"설립일", units="days"))/365, digits=1)
str(years.in.business)
head(years.in.business)
doorae0924$"업력" <- years.in.business
str(doorae0924)
```

* 사업자등록여부와 업력을 함께 새로운 data frame 으로

```{r, business registration}
doorae0924$"사업자등록여부" <- factor(ifelse(doorae0924$"사업자등록" == "NA", "No", "Yes"), levels = c("Yes", "No"))
doorae0924.ys <- data.frame(status=factor(doorae0924$"공동체상태", levels = c("창업준비", "경영개선")), years = doorae0924$"업력")
```

### Save data

```{r save_image}
save.image("./doorae_new_data.RData")
```                        