---
title : "tapply vs aggregate"
author : "coop2711"
date : "`r Sys.Date()`"
output: 
  html_document: 
    number_sections: yes
    toc: yes
---
# tapply vs aggregate

## kable and pander

### packages

```{r, library-packages}
getwd()
library(pander)
library(knitr)
library(RCurl)
library(data.table)
# panderOptions()
panderOptions("table.split.table", Inf)
options(width=180)
```

### tapply 

```{r, tapply-pander}
# githubURL <- "https://github.com/kwlee58/Doorae/R/doorae_new.rda"
# load(url(githubURL))
# tmpfile <- tempfile()
# download.file(githubURL, destfile=tmpfile, method="curl")
# url.data <- tmpfile
# load(url.data)
# getURLContent(githubURL, binary=TRUE)
# load("~/Desktop/Works/Class/Case_studies_in_stat/R.WD/Doorae_Class/R/doorae_new1015.rda")
load("~/Desktop/Works/Class/Case_studies_in_stat/R.WD/Doorae_Class/R/doorae_new.rda")
tapply.ys <- tapply(doorae$"업력", doorae$"공동체상태", summary)
pander(tapply.ys[[1]])
pander(tapply.ys[1])
str(tapply.ys[1])
str(tapply.ys[[1]])
names(tapply.ys[[1]])
names(tapply.ys[[1]]) <- c("최소값", "제1사분위수", "중위수", "산술평균", "제3사분위수", "최대값")
names(tapply.ys[[2]]) <- c("최소값", "제1사분위수", "중위수", "산술평균", "제3사분위수", "최대값")
tapply.ys
pander(tapply.ys)
```

### aggregate

```{r, aggregate-kable}
doorae.ag <- aggregate(업력~공동체상태, data=doorae, summary)
names(aggregate(업력~공동체상태, data=doorae, summary))
xtabs(업력~공동체상태, doorae.ag)
doorae.xtab <- xtabs(업력~공동체상태, doorae.ag)
str(doorae.xtab)
rownames(doorae.xtab)
colnames(doorae.xtab)
dimnames(doorae.xtab)<-list("공동체상태"=rownames(doorae.xtab), "업력"=names(tapply.ys[[1]]))
str(doorae.xtab)
kable(xtabs(업력~공동체상태, doorae.ag), caption="<공동체상태와 업력>")
kable(doorae.xtab, caption="<공동체상태와 업력>")
```

